name: chococsv-apache

volumes:
    db-volume:

networks:
    appnet:
    dbnet:

services:
    j4x:
        image: joomla:4.4-php8.1-apache
        restart: unless-stopped
        environment:
            JOOMLA_DB_HOST: db
            JOOMLA_DB_PASSWORD: example
            JOOMLA_SITE_NAME: CHOCOCSV J44X
            JOOMLA_ADMIN_USER: Chococsv Hero J44x
            JOOMLA_ADMIN_USERNAME: pro-chococsv-j44x
            JOOMLA_ADMIN_PASSWORD: Chococsv#Secured
            JOOMLA_ADMIN_EMAIL: pro.chococsv.j44x@example.org
            JOOMLA_SMTP_HOST: "fakesmtp:1025"
            JOOMLA_EXTENSIONS_PATHS: "./extensions"
        ports:
            - "127.0.0.1:54490:80/tcp"
        volumes:
            - "./j4x:/var/www/html"
            - "./zzz-custom.ini:/usr/local/etc/php/conf.d/zzz-custom.ini"
        networks:
            - appnet
            - dbnet
        depends_on:
            db:
                condition: service_healthy
            fakesmtp:
                condition: service_started
    j51x:
        image: joomla:5.1-php8.1-apache
        restart: unless-stopped
        environment:
            JOOMLA_DB_HOST: db
            JOOMLA_DB_PASSWORD: example
            JOOMLA_SITE_NAME: CHOCOCSV J51X
            JOOMLA_ADMIN_USER: Chococsv Hero J51x
            JOOMLA_ADMIN_USERNAME: pro-chococsv-j51x
            JOOMLA_ADMIN_PASSWORD: Chococsv#Secured
            JOOMLA_ADMIN_EMAIL: pro.chococsv.j51x@example.org
            JOOMLA_SMTP_HOST: "fakesmtp:1025"
            JOOMLA_EXTENSIONS_PATHS: "./extensions"
        ports:
            - "127.0.0.1:54510:80/tcp"
        volumes:
            - "./j51x:/var/www/html"
            - "./zzz-custom.ini:/usr/local/etc/php/conf.d/zzz-custom.ini"
        networks:
            - appnet
            - dbnet
        depends_on:
            db:
                condition: service_healthy
            fakesmtp:
                condition: service_started

    j52x:
        image: joomla:5.2-php8.1-apache
        restart: unless-stopped
        environment:
            JOOMLA_DB_HOST: db
            JOOMLA_DB_PASSWORD: example
            JOOMLA_SITE_NAME: CHOCOCSV J52X
            JOOMLA_ADMIN_USER: Chococsv Hero J52x
            JOOMLA_ADMIN_USERNAME: pro-chococsv-j52x
            JOOMLA_ADMIN_PASSWORD: Chococsv#Secured
            JOOMLA_ADMIN_EMAIL: pro.chococsv.j52x@example.org
            JOOMLA_SMTP_HOST: "fakesmtp:1025"
            JOOMLA_EXTENSIONS_PATHS: "./extensions"
        ports:
            - "127.0.0.1:54520:80/tcp"
        volumes:
            - "./j52x:/var/www/html"
            - "./zzz-custom.ini:/usr/local/etc/php/conf.d/zzz-custom.ini"
        networks:
            - appnet
            - dbnet
        depends_on:
            db:
                condition: service_healthy
            fakesmtp:
                condition: service_started
    db:
        image: mysql:8.4
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: example
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10
        ports:
            - "127.0.0.1:54306:3306/tcp"
            - "127.0.0.1:54360:33060/tcp"
        volumes:
            - "db-volume:/var/lib/mysql"
        networks:
            - dbnet
    fakesmtp:
        image: mailhog/mailhog:v1.0.1
        restart: unless-stopped
        ports:
            - "127.0.0.1:54880:1080/tcp"
        networks:
            - appnet
