name: chococsv-apache

volumes:
  j4x-volume:
  j51x-volume:
  db-volume:

networks:
  appnet:
  dbnet:

services:
  j4x:
    image: joomla:4.4-php8.1-apache
    restart: unless-stopped
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_PASSWORD: example
    ports:
      - "127.0.0.1:54490:80/tcp"
    volumes:
      - "j4x-volume:/var/www/html"
      - "./zzz-custom.ini:/usr/local/etc/php/conf.d/zzz-custom.ini"
    networks:
      - appnet
      - dbnet
    depends_on:
      db:
        condition: service_healthy
  j51x:
    image: joomla:5.1-php8.1-apache
    restart: unless-stopped
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_PASSWORD: example
    ports:
      - "127.0.0.1:54590:80/tcp"
    volumes:
      - "j51x-volume:/var/www/html"
      - "./zzz-custom.ini:/usr/local/etc/php/conf.d/zzz-custom.ini"
    networks:
      - appnet
      - dbnet
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - "127.0.0.1:54306:3306/tcp"
      - "127.0.0.1:54360:33060/tcp"
    volumes:
      - "db-volume:/var/lib/mysql"
    networks:
      - dbnet
